### PR TITLE
Add support for Signal database version 167

### PR DESCRIPTION
**Pull request by JonaRL**
With these changes I was able to successfully run the program on a backup that had signal database version 167.
Note that reactions are still completely broken. In addition, some issues may just be worked around at this point and therefore require a thorough fix at another time.

### CODE REVIEW

**Comment by catdevrandom** [comment]
Hi, I just tested your patch with a database version 167 but still got this error: "sqlite3.OperationalError: no such table: sqlite_schema"

I changed line 685 in core.py to:

`qry = db.execute("SELECT COUNT(*) FROM sqlite_sequence")`

and it seemed to have gone through.

**Comment by JonaRL** [comment]
I just tested again with a database version 167 backup and got no errors. However, I can confirm that, looking at the database, there indeed is a table called `sqlite_sequence`, but no table called `sqlite_schema`, so they seem to have actually changed the name. Might just not be relevant for the backup I tested with.

**Comment by Skaronator** [comment]
Version 171 breaking things further fyi:

````
$ signal2html -i . -o signal_html/
2023-01-18 13:42:23 | INFO - This is signal2html version 0.2.11
2023-01-18 13:42:23 | INFO - Found Signal database version: 171.
2023-01-18 13:42:23 | WARNING - This database version is untested, please report errors.
Traceback (most recent call last):
  File "/home/niklas/.local/bin/signal2html", line 8, in <module>
    sys.exit(main())
  File "/home/niklas/.local/lib/python3.9/site-packages/signal2html/__main__.py", line 20, in main
    sys.exit(main())
  File "/home/niklas/.local/lib/python3.9/site-packages/signal2html/ui.py", line 37, in main
    process_backup(args.input_dir, args.output_dir)
  File "/home/niklas/.local/lib/python3.9/site-packages/signal2html/core.py", line 707, in process_backup
    populate_thread(
  File "/home/niklas/.local/lib/python3.9/site-packages/signal2html/core.py", line 659, in populate_thread
    sms_records = get_sms_records(db, thread, addressbook, versioninfo)
  File "/home/niklas/.local/lib/python3.9/site-packages/signal2html/core.py", line 92, in get_sms_records
    sms_qry = db.execute(
sqlite3.OperationalError: no such table: sms
```

**Comment by 0nobody0** [comment]
i also received the same `no such table: sms` error with database version 170 using https://github.com/JonaRL/signal2html

**Comment by ashvnv** [comment]
I was able to make it work. In core.py just comment line no 659 and 668. It is a quick hack though. I guess if you are not using sms then this error pops.
image

**Comment by 0nobody0** [comment]
thank you, i hadn't had a chance to peek at the code yet...this seems to do the trick for me

> I was able to make it work. In core.py just comment line no 659 and 668. It is a quick hack though. I guess if you are not using sms then this error pops.

**Pull request closed without merging**
